home_page_ui <- function(id) {
    nav_panel(
        "Home",
        tags$h2("1. Introduction"),
        tags$p(
            "This Shiny web app contains some useful apps (e.g. Graph Apps), developed for various purposes. ", tags$br(),
            "The purposes of most apps and their parameters can be directly inferred from their names. ", tags$br(),
            "Anyway, you can try each parameter yourself freely! If you find any bug or want more apps/functionalities, ", tags$br(),
            "please let me know. I'll fix or develop it as I can. At present, Graph Apps is mainly developed to visualize ", tags$br(),
            "results retrieved from ", tags$b("NeuroBorder Galaxy"), ". Of course, you can apply it to any data with ", tags$b(),
            "compatiable format."
        ),
        tags$hr(),
        tags$h2("2. Documentations"),
        tags$p(
            "Some helpful guides can be found at ", tags$a("NeuroBorder", href = "https://www.neuroborder.com"), " under ",
            tags$b("Galaxy of Blogs"), ". ", tags$br(), "If you want more useful guides, please let me know. I'll consider it seriously. ", tags$br(),
            "If indeed necessary, I'll post one for it."
        ),
        tags$hr(),
        tags$h2("3. Cautions"),
        tags$p(
            "At present, due to some technical problems in Linux server, PDFs generated by Graph Apps are truly editable in softwares, such as AI, ", tags$br(),
            "but it seems that each line of text is composed of individual, editable characters. This means that each line of text is ", tags$br(),
            "not a continuous, editable piece of text. To overcome this problem, you can download this Shiny web app from ",
            tags$a("NeuroBorder-ShinyWebApp", href = "https://github.com/yr-neurospace/NeuroBorder-ShinyWebApp"), ". ", tags$br(),
            "And then run it in your Windows/Mac laptop."
        ),
        tags$hr()
    )
}
